### ISSUE TITLE
ValueError: substring not found Error when handling look up from a dict

### ISSUE THREAD

**Issue by kevalshah90** [joyanujoy/geohasher#13]
I run into `substring not found Error` when attempting to find neighbors for a geohash. I am passing geohash of type string, as per the documentation, however, I am still seeing this issue. Here's my code: 

```

    import pandas as pd
    import pygeohash as gh
    from geolib import geohash

    geo_dict = {'9q5dx': 10, '9q9hv': 15, '9q5dv': 20}
    
    
    df = pd.DataFrame({'geohash': ['9q5dx','9qh0g','9q9hv','9q5dv'],
                       'label': ['a', 'b', 'c', 'd']})
    
    try:
        
        df['value'] = df.apply(lambda x : geo_dict[x.geohash], axis=1)
        
    except Exception as e:
        
        g = str(e)
        
        print(g, type(g))
        
        neighbours = geohash.neighbours(g)

```

 
    `9qh0g' <class 'str'>`

    
    ValueError                                Traceback (most recent call last)
    <ipython-input-488-e803623c09eb> in <module>
         18     print(g, type(g))
         19 
    ---> 20     neighbours = geohash.neighbours(g)
         21 
    
    ~/opt/anaconda3/lib/python3.8/site-packages/geolib/geohash.py in neighbours(geohash)
        254     >>> gcpuypm
        255     """
    --> 256     n = adjacent(geohash, 'n')
        257     ne = adjacent(n, 'e')
        258     e = adjacent(geohash, 'e')
    
    ~/opt/anaconda3/lib/python3.8/site-packages/geolib/geohash.py in adjacent(geohash, direction)
        232         parent = adjacent(parent, direction)
        233 
    --> 234     index = neighbour[direction][typ].index(last_char)
        235     return parent + base32[index]
        236 
    
        ValueError: substring not found

When I hard code it, I get the expect result:

    
     geohash.neighbours('9qh0g')
    
     Neighbours(n='9qh15', ne='9qh1h', e='9qh0u', se='9qh0s', s='9qh0e', sw='9qh0d', w='9qh0f', nw='9qh14')

**Comment by joyanujoy** [comment]
Hi,

The error has nothing to do with the library. Your code snippets have errors. neighbours method expects geoshash as a string. Instead you are passing "g" which is an exception. 

This works:

```python

for hash in ['9q5dx','9qh0g','9q9hv','9q5dv']:
      neighbours = geohash.neighbours(hash)
      print(neighbours)


```
